/*
 * Copyright © "Open Digital Education", 2015
 *
 * This program is published by "Open Digital Education".
 * You must indicate the name of the software and the company in any production /contribution
 * using the software and indicate on the home page of the software industry in question,
 * "powered by Open Digital Education" with a reference to the website: https://opendigitaleducation.com/.
 *
 * This program is free software, licensed under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, version 3 of the License.
 *
 * You can redistribute this application and/or modify it since you respect the terms of the GNU Affero General Public License.
 * If you modify the source code and then use this modified source code in your creation, you must make available the source code of your modifications.
 *
 * You should have received a copy of the GNU Affero General Public License along with the software.
 * If not, please see : <http://www.gnu.org/licenses/>. Full compliance requires reading the terms of this license and following its directives.

 */

package org.entcore.auth.services;

import org.entcore.common.user.UserInfos;

import io.vertx.core.Future;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.core.json.JsonObject;

public interface MfaService {
	/**
	 * Start a new MFA workflow => send a code by email or SMS.
	 * @return mfaState {
		"state": "outdated | pending | valid", 
		"tries": number of remaining retries before code becomes outdated,
		"ttl": number of seconds remaining before expiration of the code
		}
	 */
	public Future<JsonObject> startMfaWorkflow(final HttpServerRequest request, final JsonObject session, final UserInfos userInfos);

	/**
	 * Same as above, but the code may be sent through another channel than the user's one
	 * (e.g. "email" when the authenticator app is not at hand).
	 * @param channel "email" | "sms" | null for the user's own channel
	 */
	public Future<JsonObject> startMfaWorkflow(final HttpServerRequest request, final JsonObject session, final UserInfos userInfos, final String channel);

	/**
	 * Try to validate an MFA with a code
	 * @param key
	 * @return mfaState {
		"state": "outdated | pending | valid", 
		"tries"?: number of remaining retries before code becomes outdated,
		"ttl"?: number of seconds remaining before expiration of the code
		}
	 */
	public Future<JsonObject> tryCode(final HttpServerRequest request, final UserInfos userInfos, final String key);

	/**
	 * Verify a TOTP code against the stored secret of a given user (admin use).
	 * @param userId the target user's id
	 * @param code the 6-digit TOTP code to verify
	 * @return { "state": "valid" | "invalid" | "not.enrolled" }
	 */
	public Future<JsonObject> verifyTotpForUser(final String userId, final String code);

	/**
	 * Second-factor settings of the connected user.
	 * @return { types: string[], active: boolean, preferred: string|null, channel: string|null,
	 *   hasTotp: boolean, totpManagedByAdmin: boolean, email: masked string|null, mobile: masked string|null }
	 */
	public Future<JsonObject> getSettings(final UserInfos userInfos);

	/** Choose the second factor ("email" | "sms" | "totp") among the configured and usable ones. */
	public Future<JsonObject> setPreferredType(final UserInfos userInfos, final String type);

	/**
	 * Generate a new TOTP secret, pending until confirmed with a first code.
	 * Without a session that already passed MFA, a proof code is emailed and required at confirmation.
	 * @return { secret: base32 string, uri: otpauth URI, period: number, expiresIn: seconds,
	 *   proof?: "email", proofTarget?: masked email }
	 */
	public Future<JsonObject> startTotpEnrollment(final HttpServerRequest request, final UserInfos userInfos,
			final String issuer, final String deviceName, final boolean sessionProven);

	/**
	 * Confirm the pending TOTP secret with a code generated by the app (and the emailed proof code if required).
	 * @return { state: "valid" | "invalid", field?: "code" | "emailCode", tries?, outdated? }
	 */
	public Future<JsonObject> confirmTotpEnrollment(final HttpServerRequest request, final UserInfos userInfos,
			final String code, final String emailCode, final boolean sessionProven);

	/** Remove a self-enrolled TOTP secret. */
	public Future<JsonObject> removeTotp(final UserInfos userInfos);
}
